version: 0.1.{build}

branches:
    only:
        - master
        - develop

install:
    - git submodule -q update --init

before_build:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 12" -T "v120" --build-dir "." ..

build:
    project: build\bft.sln
